proto_outdir = "./proto"

[[dependencies]]
  target = "github.com/protocolbuffers/protobuf"
  branch = "master"

[[dependencies]]
  target = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "v1.2.2"
  path = "grpc-gateway/examplepb"

[[dependencies]]
  target = "github.com/kubernetes/helm"
  revision = "v2.8.1"
  ignores = ["./release", "./rudder", "./services", "./version"]